### ISSUE TITLE
Correct sponsors

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/OpenConLondon_ReproHack_app#2]
Who are the sponsors this year?

**Comment by annakrystalli** [comment]
@Protohedgehog are ScienceOpwn and OpenAIRE still sponsors?

**Comment by Protohedgehog** [comment]
We're co-organisers. Tony is at Know Center though now, so not OpenAire. Main sponsors are, I think, Altmetric, Overleaf and Figshare.

**Comment by annakrystalli** [comment]
OK just trying to make sure I've got the right logos on the page.  So Overleaf, Altmetric, Figshare and of course Digital Science right?

**Comment by Protohedgehog** [comment]
That should do it! We can always ask Laura to confirm :)

**Comment by annakrystalli** [comment]
💯
